In [66]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [67]:
df = pd.read_csv('diabetes_prediction_dataset.csv')

In [68]:
df.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0

In [69]:
df.drop(['blood_glucose_level'], axis='columns', inplace=True)

In [70]:
df.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,0
1,Female,54.0,0,0,No Info,27.32,6.6,0
2,Male,28.0,0,0,never,27.32,5.7,0
3,Female,36.0,0,0,current,23.45,5.0,0
4,Male,76.0,1,1,current,20.14,4.8,0

In [71]:
df.smoking_history.unique()

array(['never', 'No Info', 'current', 'former', 'ever', 'not current'],
      dtype=object)

In [72]:
df.smoking_history = df.smoking_history.map({'never':1, 'No Info':2, 'current':3, 'former':4, 'ever':5, 'not current':6})

In [73]:
df.gender = df.gender.map({'Female': 0 , 'Male': 1})

In [74]:
df.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,diabetes
0,0.0,80.0,0,1,1,25.19,6.6,0
1,0.0,54.0,0,0,2,27.32,6.6,0
2,1.0,28.0,0,0,1,27.32,5.7,0
3,0.0,36.0,0,0,3,23.45,5.0,0
4,1.0,76.0,1,1,3,20.14,4.8,0

In [75]:
corr = round(df.corr(), 4)
corr.style.background_gradient()

In [91]:
data_x = df.drop(['diabetes'], axis='columns')
data_y = df.diabetes

In [92]:
data_x

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level
0,0.0,80.0,0,1,1,25.19,6.6
1,0.0,54.0,0,0,2,27.32,6.6
2,1.0,28.0,0,0,1,27.32,5.7
3,0.0,36.0,0,0,3,23.45,5.0
4,1.0,76.0,1,1,3,20.14,4.8
...,...,...,...,...,...,...,...
99995,0.0,80.0,0,0,2,27.32,6.2
99996,0.0,2.0,0,0,2,17.37,6.5
99997,1.0,66.0,0,0,4,27.83,5.7
99998,0.0,24.0,0,0,1,35.42,4.0
99999,0.0,57.0,0,0,3,22.43,6.6

In [93]:
data_y

0        0
1        0
2        0
3        0
4        0
        ..
99995    0
99996    0
99997    0
99998    0
99999    0
Name: diabetes, Length: 100000, dtype: int64

In [94]:
df.describe()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,diabetes
count,99982.000000,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,0.414375,41.885856,0.07485,0.039420,2.306950,27.320767,5.527507,0.085000
std,0.492616,22.516840,0.26315,0.194593,1.454501,6.636783,1.070672,0.278883
min,0.000000,0.080000,0.00000,0.000000,1.000000,10.010000,3.500000,0.000000
25%,0.000000,24.000000,0.00000,0.000000,1.000000,23.630000,4.800000,0.000000
50%,0.000000,43.000000,0.00000,0.000000,2.000000,27.320000,5.800000,0.000000
75%,1.000000,60.000000,0.00000,0.000000,3.000000,29.580000,6.200000,0.000000
max,1.000000,80.000000,1.00000,1.000000,6.000000,95.690000,9.000000,1.000000

In [95]:
data_x.gender = data_x.gender.fillna(data_x.gender.mean())

In [96]:
# Ahora inicializamos el modelo
decission_model = DecisionTreeClassifier()

In [97]:
train_x, test_x, train_y, test_y = train_test_split(data_x, data_y, test_size=0.1)

In [98]:
# Entrenamos el modelo
decission_model.fit(train_x, train_y)

c:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
c:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
c:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
c:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
c:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):

DecisionTreeClassifier()

In [99]:
y_predicted = decission_model.predict(test_x)

c:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
c:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
c:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):

In [181]:
print(f'Score del modelo: {round(decission_model.score(test_x, test_y), 4) * 100}%')

Score del modelo: 92.56%

c:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
c:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
c:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
c:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
c:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
c:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
c:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
c:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
c:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):

In [182]:
result = ['No tiene diabetes', 'Tiene diabetes']
gender = {0: 'None', 1: 'Masculino', 2: 'Femenino'}

In [183]:
def classify_diabetes(model, gender, age, bmi, bp, smoking_history, avg_glucose_level):
    predicted = model.predict([gender, age, bmi, bp, smoking_history, avg_glucose_level])
    print(f'El paciente de género {gender[gender]}, de {age} años, con un BMI de {bmi}, presión arterial de {bp}, historial de tabaquismo {smoking_history}, nivel de glucosa promedio {avg_glucose_level}: {result[predicted[0]]}')

In [184]:
classify_diabetes(decission_model, gender=1, age=50, bmi=30, bp=100, smoking_history=1, avg_glucose_level=120)

c:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

ValueError: Expected 2D array, got 1D array instead:
array=[  1.  50.  30. 100.   1. 120.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.