In [32]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [33]:
## cargando el dataset
df = pd.read_csv('diabetes_prediction_dataset.csv')

In [34]:
## ver los registros que tiene el dataset
df.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0

In [35]:
df.drop(['blood_glucose_level'], axis='columns', inplace=True)

In [36]:
df.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,0
1,Female,54.0,0,0,No Info,27.32,6.6,0
2,Male,28.0,0,0,never,27.32,5.7,0
3,Female,36.0,0,0,current,23.45,5.0,0
4,Male,76.0,1,1,current,20.14,4.8,0

In [37]:
df.smoking_history.unique()

array(['never', 'No Info', 'current', 'former', 'ever', 'not current'],
      dtype=object)

In [38]:
df.smoking_history = df.smoking_history.map({'never':1, 'No Info':2, 'current':3, 'former':4, 'ever':5, 'not current':6})

In [39]:
df.gender = df.gender.map({'Female': 0 , 'Male': 1})

In [10]:
df.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,diabetes
0,0.0,80.0,0,1,1,25.19,6.6,0
1,0.0,54.0,0,0,2,27.32,6.6,0
2,1.0,28.0,0,0,1,27.32,5.7,0
3,0.0,36.0,0,0,3,23.45,5.0,0
4,1.0,76.0,1,1,3,20.14,4.8,0

In [40]:
corr = round(df.corr(), 4)
corr.style.background_gradient()

In [41]:
data_x = df.drop(['diabetes'], axis='columns')
data_y = df.diabetes

In [52]:
train_x, test_x, train_y, test_y = train_test_split(data_x, data_y, test_size=0.1)

In [55]:
k_neighbors = KNeighborsClassifier()

In [56]:
k_neighbors.fit(train_x, train_y)

c:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
c:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
c:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):

ValueError: Input X contains NaN.
KNeighborsClassifier does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values