In [5]:
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np
import seaborn as sns

In [6]:
df = pd.read_csv('Invistico_Airline.csv')

In [7]:
df.dtypes

satisfaction                          object
Customer Type                         object
Age                                    int64
Type of Travel                        object
Class                                 object
Flight Distance                        int64
Seat comfort                           int64
Departure/Arrival time convenient      int64
Food and drink                         int64
Gate location                          int64
Inflight wifi service                  int64
Inflight entertainment                 int64
Online support                         int64
Ease of Online booking                 int64
On-board service                       int64
Leg room service                       int64
Baggage handling                       int64
Checkin service                        int64
Cleanliness                            int64
Online boarding                        int64
Departure Delay in Minutes             int64
Arrival Delay in Minutes             float64
dtype: object

In [8]:
df.satisfaction.unique()

array(['satisfied', 'dissatisfied'], dtype=object)

In [9]:
df.satisfaction = df.satisfaction.map({'satisfied': 1, 'dissatisfied': 2})

In [10]:
df['Customer Type'].unique()

array(['Loyal Customer', 'disloyal Customer'], dtype=object)

In [11]:
df['Customer Type'] = df['Customer Type'].map({'Loyal Customer': 1, 'disloyal Customer': 2})

In [12]:
df['Type of Travel'].unique()

array(['Personal Travel', 'Business travel'], dtype=object)

In [13]:
df['Type of Travel'] = df['Type of Travel'].map({'Personal Travel': 1, 'Business travel': 2})

In [14]:
df.Class.unique()

array(['Eco', 'Business', 'Eco Plus'], dtype=object)

In [15]:
df.Class = df.Class.map({'Eco': 1, 'Business': 2, 'Eco Plus': 3})

In [16]:
df.dtypes

satisfaction                           int64
Customer Type                          int64
Age                                    int64
Type of Travel                         int64
Class                                  int64
Flight Distance                        int64
Seat comfort                           int64
Departure/Arrival time convenient      int64
Food and drink                         int64
Gate location                          int64
Inflight wifi service                  int64
Inflight entertainment                 int64
Online support                         int64
Ease of Online booking                 int64
On-board service                       int64
Leg room service                       int64
Baggage handling                       int64
Checkin service                        int64
Cleanliness                            int64
Online boarding                        int64
Departure Delay in Minutes             int64
Arrival Delay in Minutes             float64
dtype: object

In [17]:
df['Arrival Delay in Minutes'] = df['Arrival Delay in Minutes'].fillna(df['Arrival Delay in Minutes'].mean())

In [18]:
df.describe()

,satisfaction,Customer Type,Age,Type of Travel,Class,Flight Distance,Seat comfort,Departure/Arrival time convenient,Food and drink,Gate location,...,Online support,Ease of Online booking,On-board service,Leg room service,Baggage handling,Checkin service,Cleanliness,Online boarding,Departure Delay in Minutes,Arrival Delay in Minutes
count,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,...,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000
mean,1.452672,1.183092,39.427957,1.690584,1.623514,1981.409055,2.838597,2.990645,2.851994,2.990422,...,3.519703,3.472105,3.465075,3.485902,3.695673,3.340807,3.705759,3.352587,14.713713,15.091129
std,0.497757,0.386743,15.119360,0.462255,0.616170,1027.115606,1.392983,1.527224,1.443729,1.305970,...,1.306511,1.305560,1.270836,1.292226,1.156483,1.260582,1.151774,1.298715,38.071126,38.407410
min,1.000000,1.000000,7.000000,1.000000,1.000000,50.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,1.000000,27.000000,1.000000,1.000000,1359.000000,2.000000,2.000000,2.000000,2.000000,...,3.000000,2.000000,3.000000,2.000000,3.000000,3.000000,3.000000,2.000000,0.000000,0.000000
50%,1.000000,1.000000,40.000000,2.000000,2.000000,1925.000000,3.000000,3.000000,3.000000,3.000000,...,4.000000,4.000000,4.000000,4.000000,4.000000,3.000000,4.000000,4.000000,0.000000,0.000000
75%,2.000000,1.000000,51.000000,2.000000,2.000000,2544.000000,4.000000,4.000000,4.000000,4.000000,...,5.000000,5.000000,4.000000,5.000000,5.000000,4.000000,5.000000,4.000000,12.000000,13.000000
max,2.000000,2.000000,85.000000,2.000000,3.000000,6951.000000,5.000000,5.000000,5.000000,5.000000,...,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,1592.000000,1584.000000

In [19]:
data_x = df.drop(['satisfaction', 'Departure/Arrival time convenient', 'Gate location', 'Arrival Delay in Minutes', 'Flight Distance'], axis='columns')
data_y = df.satisfaction

In [20]:
forest = RandomForestClassifier()

In [21]:
forest.fit(data_x, data_y)

RandomForestClassifier()

In [22]:
print(f'Score del modelo: {round(forest.score(data_x, data_y), 4) * 100}%')

Score del modelo: 99.99%

In [23]:
data_x

,Customer Type,Age,Type of Travel,Class,Seat comfort,Food and drink,Inflight wifi service,Inflight entertainment,Online support,Ease of Online booking,On-board service,Leg room service,Baggage handling,Checkin service,Cleanliness,Online boarding,Departure Delay in Minutes
0,1,65,1,1,0,0,2,4,2,3,3,0,3,5,3,2,0
1,1,47,1,2,0,0,0,2,2,3,4,4,4,2,3,2,310
2,1,15,1,1,0,0,2,0,2,2,3,3,4,4,4,2,0
3,1,60,1,1,0,0,3,4,3,1,1,0,1,4,1,3,0
4,1,70,1,1,0,0,4,3,4,2,2,0,2,4,2,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129875,2,29,1,1,5,5,2,5,2,2,3,3,4,4,4,2,0
129876,2,63,1,2,2,2,2,1,1,3,2,3,3,1,2,1,174
129877,2,69,1,1,3,3,3,2,2,4,4,3,4,2,3,2,155
129878,2,66,1,1,3,3,3,2,2,3,3,2,3,2,1,2,193
129879,2,38,1,1,3,3,3,3,3,4,5,5,5,3,3,3,185

In [24]:
customer_type = ['None', 'Leal', 'Desleal']
type_travel = ['None', 'Viaje Personal', 'Viaje de Negocios']
clase = ['None', 'Eco', 'Business', 'Eco Plus']
state = ['insatisfecho', 'satisfecho']

def passenger_satisfaction_classifier(model, customer, age, travel, p_class, sit_comfort, food_and_drink, wifi, entertaiment, online_support, online_booking, service, leg_room, baggage_handling, checkin, cleanliness, online_boarding, departure_delay):
    predicted = model.predict([[customer, age, travel, p_class, sit_comfort, food_and_drink, wifi, entertaiment, online_support, online_booking, service, leg_room, baggage_handling, checkin, cleanliness, online_boarding, departure_delay]])
    print(f'El pasajero de tipo: {customer_type[customer]}, de {age} años, que hizo un {type_travel[travel]}, en clase {clase[p_class]}, y con calificaciones de comodidad: {sit_comfort}, comida y bebida: {food_and_drink}, wifi: {wifi}, entretenimiento: {entertaiment}, soporte en línea: {online_support}, reserva en línea: {online_booking}, servicio a bordo: {service}, espacio para las piernas: {leg_room}, manejo de equipaje: {baggage_handling}, check-in: {checkin}, limpieza: {cleanliness}, abordaje en línea: {online_boarding}, y demora en la salida de: {departure_delay} minutos, está: {state[predicted[0]]} con su experiencia de vuelo.')

In [25]:
passenger_satisfaction_classifier(forest, 1, 65, 1, 2, 1, 1, 3, 4, 2, 3, 3, 3, 3, 5, 3, 2, 3)

El pasajero de tipo: Leal, de 65 años, que hizo un Viaje Personal, en clase Business, y con calificaciones de comodidad: 1, comida y bebida: 1, wifi: 3, entretenimiento: 4, soporte en línea: 2, reserva en línea: 3, servicio a bordo: 3, espacio para las piernas: 3, manejo de equipaje: 3, check-in: 5, limpieza: 3, abordaje en línea: 2, y demora en la salida de: 3 minutos, está: satisfecho con su experiencia de vuelo.

c:\NurVI\Algoritmica Avanzada\pandas_intro\pandas_env\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(