In [21]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

import pandas as pd
import numpy as np
import matplotlib as plt

In [22]:
df = pd.read_csv("dataset_fish.csv")

In [23]:
# Verificamos data frame
df.head(76)

   Species  Weight  Length1  Length2  Length3   Height   Width
0    Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1    Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2    Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3    Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4    Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
..     ...     ...      ...      ...      ...      ...     ...
71  Parkki   300.0     24.0     26.0     29.0  11.3680  4.2340
72   Perch     5.9      7.5      8.4      8.8   2.1120  1.4080
73   Perch    32.0     12.5     13.7     14.7   3.5280  1.9992
74   Perch    40.0     13.8     15.0     16.0   3.8240  2.4320
75   Perch    51.5     15.0     16.2     17.2   4.5924  2.6316

[76 rows x 7 columns]

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Species  159 non-null    object
 1   Weight   159 non-null    float64
 2   Length1  159 non-null    float64
 3   Length2  159 non-null    float64
 4   Length3  159 non-null    float64
 5   Height   159 non-null    float64
 6   Width    159 non-null    float64
dtypes: float64(6), object(1)
memory usage: 8.8+ KB

In [25]:
df.Weight.unique()

array([ 242. ,  290. ,  340. ,  363. ,  430. ,  450. ,  500. ,  390. ,
        475. ,  600. ,  700. ,  610. ,  650. ,  575. ,  685. ,  620. ,
        680. ,  725. ,  720. ,  714. ,  850. , 1000. ,  920. ,  955. ,
        925. ,  975. ,  950. ,   40. ,   69. ,   78. ,   87. ,  120. ,
          0. ,  110. ,  150. ,  145. ,  160. ,  140. ,  169. ,  161. ,
        200. ,  180. ,  272. ,  270. ,  306. ,  540. ,  800. ,   55. ,
         60. ,   90. ,  170. ,  273. ,  300. ,    5.9,   32. ,   51.5,
         70. ,  100. ,   80. ,   85. ,  115. ,  125. ,  130. ,  135. ,
        225. ,  188. ,  197. ,  218. ,  260. ,  265. ,  250. ,  320. ,
        514. ,  556. ,  840. ,  690. ,  900. ,  820. , 1015. , 1100. ,
        345. ,  456. ,  510. ,  567. ,  770. , 1250. , 1600. , 1550. ,
       1650. ,    6.7,    7.5,    7. ,    9.7,    9.8,    8.7,   10. ,
          9.9,   12.2,   13.4,   19.7,   19.9])

In [26]:
#mapeamos
df.Species = df.Species.map({"Bream":1,"Roach":2,"Whitefish":3,"Parkki":4,"Perch":5,"Pike":6,"Smelt":7})

In [27]:
df.describe()

,Species,Weight,Length1,Length2,Length3,Height,Width
count,159.000000,159.000000,159.000000,159.000000,159.000000,159.000000,159.000000
mean,3.880503,398.326415,26.247170,28.415723,31.227044,8.970994,4.417486
std,2.026298,357.978317,9.996441,10.716328,11.610246,4.286208,1.685804
min,1.000000,0.000000,7.500000,8.400000,8.800000,1.728400,1.047600
25%,2.000000,120.000000,19.050000,21.000000,23.150000,5.944800,3.385650
50%,5.000000,273.000000,25.200000,27.300000,29.400000,7.786000,4.248500
75%,5.000000,650.000000,32.700000,35.500000,39.650000,12.365900,5.584500
max,7.000000,1650.000000,59.000000,63.400000,68.000000,18.957000,8.142000

In [28]:
corr = round(df.corr(),4)
corr.style.background_gradient()

In [29]:
x = df.drop(["Species","Weight"] ,axis=1)
y = df.Weight

In [30]:
x

     Length1  Length2  Length3   Height   Width
0       23.2     25.4     30.0  11.5200  4.0200
1       24.0     26.3     31.2  12.4800  4.3056
2       23.9     26.5     31.1  12.3778  4.6961
3       26.3     29.0     33.5  12.7300  4.4555
4       26.5     29.0     34.0  12.4440  5.1340
..       ...      ...      ...      ...     ...
154     11.5     12.2     13.4   2.0904  1.3936
155     11.7     12.4     13.5   2.4300  1.2690
156     12.1     13.0     13.8   2.2770  1.2558
157     13.2     14.3     15.2   2.8728  2.0672
158     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 5 columns]

In [31]:
train_x,test_x,train_y,test_y  = train_test_split(x,y,test_size=0.20)

In [32]:
#iniciamos el modelo
linear = LinearRegression()

In [33]:
#entrenamos el modelo
linear.fit(train_x,train_y)

LinearRegression()

In [34]:
y_predicted = linear.predict(test_x)

In [35]:
print(f"calificacion de prediccion {linear.score(test_x,test_y)}")

calificacion de prediccion 0.8950864135589287

In [36]:
len1 = 15.0
len2 = 16.2	
len3 = 17.2
height = 4.5924
width = 5.6316

In [37]:
train_x

     Length1  Length2  Length3   Height   Width
72       7.5      8.4      8.8   2.1120  1.4080
27      32.7     36.0     41.5  16.5170  5.8515
142     56.0     60.0     64.0   9.6000  6.1440
16      30.4     33.0     38.3  14.8604  5.2854
128     30.0     32.3     34.8   5.5680  3.3756
..       ...      ...      ...      ...     ...
80      17.8     19.6     20.8   5.1376  3.0368
153     11.4     12.0     13.2   2.2044  1.1484
136     40.1     43.0     45.8   7.7860  5.1296
155     11.7     12.4     13.5   2.4300  1.2690
24      31.9     35.0     40.5  16.2405  5.5890

[127 rows x 5 columns]

In [38]:
def predict_weight(len1,len2,len3,height,width,model):
    result =model.predict([[len1,len2,len3,height,width]])
    print(f"El pez con longitud1 de {len1} , longitud2 de {len2},longitud3 de {len3}, con ancho de {width} y altura {height} debe pesar {result[0]}")

In [39]:
predict_weight(len1,len2,len3,height,width,linear)

El pez con longitud1 de 15.0 , longitud2 de 16.2,longitud3 de 17.2, con ancho de 5.6316 y altura 4.5924 debe pesar 66.51482352764947

e:\Universidad Nur\algoritmica\practico 2\linear\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [40]:
#print(f"El pez con longitud1 de {len1} , longitud2 de {len2},longitud3 de {len3}, con ancho de {width} y altura {height} debe pesar {predict_weight(len1,len2,len3,height,width,linear)}")