**Ridge es una variante de regresión lineal también conocida como "Ridge regression", para mejorar la generalización del modelo y reducir el riesgo de sobreajuste en problemas de regresión lineal múltiple.**

In [86]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge

import pandas as pd
import numpy as np

In [87]:
#Importamos el dataset y lo convertimos en un DataFrame
df = pd.read_csv("dataset_fish.csv")

In [88]:
df.head()

  Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [89]:
df.Species.unique()

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [90]:
#mapeamos columna de tipo Object categorica especies
df.Species = df.Species.map({"Bream":1,"Roach":2,"Whitefish":3,"Parkki":4,"Perch":5,"Pike":6,"Smelt":7})

In [91]:
df.tail()

     Species  Weight  Length1  Length2  Length3  Height   Width
154        7    12.2     11.5     12.2     13.4  2.0904  1.3936
155        7    13.4     11.7     12.4     13.5  2.4300  1.2690
156        7    12.2     12.1     13.0     13.8  2.2770  1.2558
157        7    19.7     13.2     14.3     15.2  2.8728  2.0672
158        7    19.9     13.8     15.0     16.2  2.9322  1.8792

In [92]:
df.describe()

,Species,Weight,Length1,Length2,Length3,Height,Width
count,159.000000,159.000000,159.000000,159.000000,159.000000,159.000000,159.000000
mean,3.880503,398.326415,26.247170,28.415723,31.227044,8.970994,4.417486
std,2.026298,357.978317,9.996441,10.716328,11.610246,4.286208,1.685804
min,1.000000,0.000000,7.500000,8.400000,8.800000,1.728400,1.047600
25%,2.000000,120.000000,19.050000,21.000000,23.150000,5.944800,3.385650
50%,5.000000,273.000000,25.200000,27.300000,29.400000,7.786000,4.248500
75%,5.000000,650.000000,32.700000,35.500000,39.650000,12.365900,5.584500
max,7.000000,1650.000000,59.000000,63.400000,68.000000,18.957000,8.142000

In [93]:
corr = df.corr()
corr.style.background_gradient()

In [94]:
#Inicializamos el modelo
ridge = Ridge()

In [95]:
#preparamos la informacion
data_x = df.drop(["Weight"],axis=1)
data_y = df.Weight

In [96]:
train_x,test_x,train_y,test_y = train_test_split(data_x,data_y,test_size=0.25)

In [97]:
#Entrenamos el modelo
ridge.fit(train_x,train_y)

Ridge()

In [98]:
#clasificacion
print(f"Score for prediction : {round(ridge.score(test_x,test_y),4)*100} %")

Score for prediction : 86.83 %

In [99]:
#predecir
all =["None","Bream","Roach","Whitefish","Parkki","Perch","Pike","Smelt"]
species = 1
length1 = 24
length2 = 18
length3 = 22
height = 11
width = 4
predict = np.round(ridge.predict([[species,length1,length2,length3,height,width]]),2)

e:\Universidad Nur\algoritmica\practico 2\linear\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

In [100]:
print(f"El pez de la especie {all[2]} con lenght1 de {length1},length2 de {length2},length3 de{length3},con un height de {height} y un width de {width} tiene un peso de {predict}")

El pez de la especie Roach con lenght1 de 24,length2 de 18,length3 de22,con un height de 11 y un width de 4 tiene un peso de [256.56]